### ISSUE TITLE
Crash on Exit

### ISSUE THREAD

**Issue by jeremyfromearth** [stimulant/Cinder-WMFVideo#1]
Applications using this library crash when exiting. For the most part this behavior is not a show-stopper, but it would be nice to have a clean exit. I consistently see: "nvoglv32.pdb not loaded" in Visual Studio 2013 Professional when this occurs. 

Occasionally, it breaks at line 136 of [PresentEngine.cpp](https://github.com/stimulant/Cinder-WMFVideo/blob/master/src/presenter/PresentEngine.cpp#L133).

**Comment by sansumbrella** [comment]
The [pdb files](http://support.microsoft.com/en-us/kb/121366) contain debug information; they don't affect how/whether an application works. VS is letting you know it doesn't have access to that debug information.

I think with pro you can click on the console info about the program databases and install the debug information, which might help you find the source of the crash.

**Comment by jeremyfromearth** [comment]
After using this in the actual project, the app no longer crashes on exit. Closing.
