### ISSUE TITLE
Volume Setting

### ISSUE THREAD

**Issue by pawansjadhav** [stimulant/Cinder-WMFVideo#4]
Hi,

We are not able to find the volume function in the code.

Please help/advice.

**Comment by endquote** [comment]
@LRitesh can you help with this question?

**Comment by LRitesh** [comment]
@pawansjadhav  there are `setVolume` and `getVolume` functions now in the latest version at: https://github.com/stimulant/Cinder-WMFVideo/blob/master/src/ciWMFVideoPlayerUtils.h#L121

Hope that helps!
